<?php

return [
    'name' => '后台管理',
    'sitename' => '网站名称',
    'sitekeyword' => '关键词,新网站',
    'sitedescription' => '这个是一个新网站',
    'languages' => [
        'zh-cn' => '中文',
        'en' => 'English',
    ],
    'beian' => '',
    'beian2' => '',
    'version' => '1.0.1',
    'timezone' => 'Asia/Shanghai',
    'forbiddenip' => '',
    'cdnurl' => '',
    'imgurl' => '',
    'vodurl' => '',
    'fixedpage' => 'dashboard',
    'categorytype' => [
        'default' => 'Default',
        'vip' => 'VIP',
    ],
    'configgroup' => [
        'basic' => 'Basic',
        'email' => 'Email',
        'sms' => 'Sms',
        'user' => 'User',
        'bin' => 'Bin',
        'project' => 'Project',
        'storage' => 'Storage',
        'dictionary' => 'Dictionary',
    ],
    'mail_type' => '1',
    'mail_smtp_host' => 'smtp.qq.com',
    'mail_smtp_port' => '465',
    'mail_smtp_user' => '10000',
    'mail_smtp_pass' => 'password',
    'mail_verify_type' => '2',
    'mail_from' => '10000@qq.com',
    'mail_sender' => 'MailerSystem',
    'login_background' => '/assets/img/qrcode.png',
    'smstype' => '1',
    'smsuser' => '1111',
    'smspass' => 'idyauwiueawhdawee',
    'smstpl' => '1',
];